sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Whrgg6....
  img:
    defalutLocation: "G:\\javaex\\cangqiong\\img\\"
    format: .jpg
  redis:
    port: 6379
    host: localhost
  wechat:
    appid: wx67397279c44f92eb
    secret: 6e6047cf0bf25106830c9c54fa8dd343